//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SportsLeagues.Interfaces;
    
    
    public partial class SportsLeaguesEntities : DbContext
    {
        public SportsLeaguesEntities()
            : base("name=SportsLeaguesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Box> Boxes { get; set; }
        public DbSet<ContactDetail> ContactDetails { get; set; }
        public DbSet<Fixture> Fixtures { get; set; }
        public DbSet<LeagueConfig> LeagueConfigs { get; set; }
        public DbSet<League> Leagues { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<Court> Courts { get; set; }
        public DbSet<Confirmation> Confirmations { get; set; }
    }
}
