//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public Box()
        {
            this.Fixtures = new HashSet<Fixture>();
        }
    
        public System.Guid Id { get; set; }
        public int Number { get; set; }
    
        public virtual ICollection<Fixture> Fixtures { get; set; }
        public virtual Season Season { get; set; }
    }
}
