//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confirmation
    {
        public System.Guid Id { get; set; }
        public ConfirmationStatusEnum Status { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Fixture Fixture { get; set; }
    }
}
