//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    
    public enum ConfirmationStatusEnum : int
    {
        Unknown = 0,
        Accept = 1,
        Cancel = 2,
        Rearrange = 3,
        Postpone = 4,
        OppNoShow = 5
    }
}
