//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        public Court()
        {
            this.LeagueConfigs = new HashSet<LeagueConfig>();
            this.Fixtures = new HashSet<Fixture>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public int Sequence { get; set; }
    
        public virtual ICollection<LeagueConfig> LeagueConfigs { get; set; }
        public virtual ICollection<Fixture> Fixtures { get; set; }
    }
}
