//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public Fixture()
        {
            this.AwayPlayers = new HashSet<Player>();
            this.HomePlayers = new HashSet<Player>();
            this.Confirmations = new HashSet<Confirmation>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
        public Nullable<int> Winner { get; set; }
        public int Sequence { get; set; }
        public Nullable<System.DateTime> ProposedDate { get; set; }
        public FixtureStatusEnum Status { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual ICollection<Player> AwayPlayers { get; set; }
        public virtual ICollection<Player> HomePlayers { get; set; }
        public virtual Court Court { get; set; }
        public virtual ICollection<Confirmation> Confirmations { get; set; }
    }
}
