//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    
    public enum FixtureStatusEnum : int
    {
        Planned = 0,
        Confirmed = 1,
        Played = 2,
        Cancelled = 3,
        Noshow = 4
    }
}
