//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public Fixture()
        {
            this.Players = new HashSet<Player>();
            this.Players1 = new HashSet<Player>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
        public Nullable<int> Winner { get; set; }
        public int Sequence { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<Player> Players1 { get; set; }
    }
}
