//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueConfig
    {
        public LeagueConfig()
        {
            this.Seasons = new HashSet<Season>();
            this.Leagues = new HashSet<League>();
            this.Courts = new HashSet<Court>();
        }
    
        public System.Guid Id { get; set; }
        public int Iterations { get; set; }
        public int BoxSize { get; set; }
        public int MovementSize { get; set; }
    
        public virtual ICollection<Season> Seasons { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<Court> Courts { get; set; }
    }
}
