//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsLeagues.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.ContactDetails = new HashSet<ContactDetail>();
            this.Leagues = new HashSet<League>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<ContactDetail> ContactDetails { get; set; }
        public virtual Fixture Fixture { get; set; }
        public virtual Fixture Fixture1 { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
    }
}
